# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common_structs.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common_structs.proto',
  package='swir_common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14\x63ommon_structs.proto\x12\x0bswir_common\"\xf9\x01\n\rInvokeRequest\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\'\n\x06method\x18\x03 \x01(\x0e\x32\x17.swir_common.HttpMethod\x12\x16\n\x0erequest_target\x18\x04 \x01(\t\x12\x38\n\x07headers\x18\x05 \x03(\x0b\x32\'.swir_common.InvokeRequest.HeadersEntry\x12\x0f\n\x07payload\x18\x06 \x01(\x0c\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"F\n\x0cInvokeResult\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.swir_common.InvokeStatus\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\xfa\x01\n\x0eInvokeResponse\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12)\n\x06result\x18\x03 \x01(\x0b\x32\x19.swir_common.InvokeResult\x12\x39\n\x07headers\x18\x05 \x03(\x0b\x32(.swir_common.InvokeResponse.HeadersEntry\x12\x13\n\x0bstatus_code\x18\x06 \x01(\x05\x12\x0f\n\x07payload\x18\x07 \x01(\x0c\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*4\n\nHttpMethod\x12\x07\n\x03GET\x10\x00\x12\x08\n\x04POST\x10\x01\x12\x07\n\x03PUT\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03*!\n\x0cInvokeStatus\x12\x06\n\x02Ok\x10\x00\x12\t\n\x05\x45rror\x10\x01\x62\x06proto3'
)

_HTTPMETHOD = _descriptor.EnumDescriptor(
  name='HttpMethod',
  full_name='swir_common.HttpMethod',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=614,
  serialized_end=666,
)
_sym_db.RegisterEnumDescriptor(_HTTPMETHOD)

HttpMethod = enum_type_wrapper.EnumTypeWrapper(_HTTPMETHOD)
_INVOKESTATUS = _descriptor.EnumDescriptor(
  name='InvokeStatus',
  full_name='swir_common.InvokeStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Ok', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Error', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=668,
  serialized_end=701,
)
_sym_db.RegisterEnumDescriptor(_INVOKESTATUS)

InvokeStatus = enum_type_wrapper.EnumTypeWrapper(_INVOKESTATUS)
GET = 0
POST = 1
PUT = 2
DELETE = 3
Ok = 0
Error = 1



_INVOKEREQUEST_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='swir_common.InvokeRequest.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='swir_common.InvokeRequest.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='swir_common.InvokeRequest.HeadersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=287,
)

_INVOKEREQUEST = _descriptor.Descriptor(
  name='InvokeRequest',
  full_name='swir_common.InvokeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='correlation_id', full_name='swir_common.InvokeRequest.correlation_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_name', full_name='swir_common.InvokeRequest.service_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='swir_common.InvokeRequest.method', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_target', full_name='swir_common.InvokeRequest.request_target', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headers', full_name='swir_common.InvokeRequest.headers', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='swir_common.InvokeRequest.payload', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INVOKEREQUEST_HEADERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=287,
)


_INVOKERESULT = _descriptor.Descriptor(
  name='InvokeResult',
  full_name='swir_common.InvokeResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='swir_common.InvokeResult.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='swir_common.InvokeResult.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=359,
)


_INVOKERESPONSE_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='swir_common.InvokeResponse.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='swir_common.InvokeResponse.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='swir_common.InvokeResponse.HeadersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=287,
)

_INVOKERESPONSE = _descriptor.Descriptor(
  name='InvokeResponse',
  full_name='swir_common.InvokeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='correlation_id', full_name='swir_common.InvokeResponse.correlation_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_name', full_name='swir_common.InvokeResponse.service_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='swir_common.InvokeResponse.result', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headers', full_name='swir_common.InvokeResponse.headers', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='swir_common.InvokeResponse.status_code', index=4,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='swir_common.InvokeResponse.payload', index=5,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INVOKERESPONSE_HEADERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=612,
)

_INVOKEREQUEST_HEADERSENTRY.containing_type = _INVOKEREQUEST
_INVOKEREQUEST.fields_by_name['method'].enum_type = _HTTPMETHOD
_INVOKEREQUEST.fields_by_name['headers'].message_type = _INVOKEREQUEST_HEADERSENTRY
_INVOKERESULT.fields_by_name['status'].enum_type = _INVOKESTATUS
_INVOKERESPONSE_HEADERSENTRY.containing_type = _INVOKERESPONSE
_INVOKERESPONSE.fields_by_name['result'].message_type = _INVOKERESULT
_INVOKERESPONSE.fields_by_name['headers'].message_type = _INVOKERESPONSE_HEADERSENTRY
DESCRIPTOR.message_types_by_name['InvokeRequest'] = _INVOKEREQUEST
DESCRIPTOR.message_types_by_name['InvokeResult'] = _INVOKERESULT
DESCRIPTOR.message_types_by_name['InvokeResponse'] = _INVOKERESPONSE
DESCRIPTOR.enum_types_by_name['HttpMethod'] = _HTTPMETHOD
DESCRIPTOR.enum_types_by_name['InvokeStatus'] = _INVOKESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InvokeRequest = _reflection.GeneratedProtocolMessageType('InvokeRequest', (_message.Message,), {

  'HeadersEntry' : _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), {
    'DESCRIPTOR' : _INVOKEREQUEST_HEADERSENTRY,
    '__module__' : 'common_structs_pb2'
    # @@protoc_insertion_point(class_scope:swir_common.InvokeRequest.HeadersEntry)
    })
  ,
  'DESCRIPTOR' : _INVOKEREQUEST,
  '__module__' : 'common_structs_pb2'
  # @@protoc_insertion_point(class_scope:swir_common.InvokeRequest)
  })
_sym_db.RegisterMessage(InvokeRequest)
_sym_db.RegisterMessage(InvokeRequest.HeadersEntry)

InvokeResult = _reflection.GeneratedProtocolMessageType('InvokeResult', (_message.Message,), {
  'DESCRIPTOR' : _INVOKERESULT,
  '__module__' : 'common_structs_pb2'
  # @@protoc_insertion_point(class_scope:swir_common.InvokeResult)
  })
_sym_db.RegisterMessage(InvokeResult)

InvokeResponse = _reflection.GeneratedProtocolMessageType('InvokeResponse', (_message.Message,), {

  'HeadersEntry' : _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), {
    'DESCRIPTOR' : _INVOKERESPONSE_HEADERSENTRY,
    '__module__' : 'common_structs_pb2'
    # @@protoc_insertion_point(class_scope:swir_common.InvokeResponse.HeadersEntry)
    })
  ,
  'DESCRIPTOR' : _INVOKERESPONSE,
  '__module__' : 'common_structs_pb2'
  # @@protoc_insertion_point(class_scope:swir_common.InvokeResponse)
  })
_sym_db.RegisterMessage(InvokeResponse)
_sym_db.RegisterMessage(InvokeResponse.HeadersEntry)


_INVOKEREQUEST_HEADERSENTRY._options = None
_INVOKERESPONSE_HEADERSENTRY._options = None
# @@protoc_insertion_point(module_scope)
